"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { PageShell } from "@/components/common/page-shell";
import { orderService } from "@/services/api";
import type { Product } from "@/types/product";

export default function CheckoutPage() { const [items, setItems] = useState<Product[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); useEffect(() => { const saved = localStorage.getItem("morrow-cart"); if (saved) setItems(JSON.parse(saved)); }, []); const placeOrder = async () => { setBusy(true); setMessage(""); try { await orderService.create(items.map((item) => ({ productId: item.id, quantity: 1 })), crypto.randomUUID()); localStorage.removeItem("morrow-cart"); setItems([]); setMessage("Your order is on its way."); } catch { setMessage("We could not place your order. Your bag is unchanged."); } finally { setBusy(false); } }; const total = items.reduce((sum, item) => sum + item.price, 0); return <PageShell><section className="mx-auto max-w-[780px] px-5 py-16 md:px-10 md:py-24"><Link href="/cart" className="text-xs uppercase tracking-[.14em] text-[var(--muted)]">← Back to bag</Link><h1 className="mt-8 font-serif text-6xl tracking-[-.06em]">Checkout.</h1>{message ? <div className="mt-12 border-t border-[var(--line)] py-10"><p className="font-serif text-3xl">{message}</p><Link href="/orders" className="mt-6 inline-block border-b border-[var(--ink)] pb-2 text-xs uppercase tracking-[.14em]">View my orders →</Link></div> : <div className="mt-12 border-t border-[var(--line)] pt-6"><div className="flex justify-between text-sm"><span>{items.length} items</span><strong>${total}</strong></div><button disabled={busy || items.length === 0} onClick={placeOrder} className="mt-10 w-full bg-[var(--ink)] px-5 py-4 text-xs font-semibold uppercase tracking-[.14em] text-white disabled:opacity-40">{busy ? "Placing order..." : items.length ? "Place order" : "Your bag is empty"}</button></div>}</section></PageShell>; }
