"use client";

import Link from "next/link";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { authService } from "@/services/api";
import { loginSchema } from "@/schemas/loginSchema";

const registerSchema = loginSchema.extend({ name: z.string().min(2, "Enter your name"), phoneNumber: z.string().min(7, "Enter a valid phone number"), confirmPassword: z.string() }).refine((values) => values.password === values.confirmPassword, { path: ["confirmPassword"], message: "Passwords must match" });
type Values = { email: string; password: string; name?: string; phoneNumber?: string; confirmPassword?: string };

export function AuthForm({ register = false }: { register?: boolean }) {
  const form = useForm<Values>({ resolver: zodResolver(register ? registerSchema : loginSchema) as never, defaultValues: register ? { name: "", email: "", phoneNumber: "", password: "", confirmPassword: "" } : { email: "", password: "" } });
  const submit = async (values: Values) => { try { const response = register ? await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: values.name, email: values.email, phoneNumber: values.phoneNumber, password: values.password, role: "user", status: "active" }) }) : await authService.login({ email: values.email, password: values.password, userType: "user" }); if (response.ok) { const next = new URLSearchParams(window.location.search).get("next"); window.location.href = register ? "/login" : next?.startsWith("/") ? next : "/products"; } else { const error = await response.json().catch(() => ({})) as { message?: string }; form.setError("root", { message: error.message ?? (response.status === 401 ? "Email or password is incorrect." : response.status === 409 ? "An account with this email already exists." : "We could not complete that request.") }); } } catch { form.setError("root", { message: "We could not reach the authentication service." }); } };
  const field = (name: "name" | "phoneNumber", label: string) => register && <div><label htmlFor={name} className="mb-2 block text-[12px] font-medium uppercase tracking-[.12em]">{label}</label><input id={name} autoComplete={name === "name" ? "name" : "tel"} {...form.register(name)} className="w-full border-b border-[var(--line)] bg-transparent px-0 py-3 outline-none focus:border-[var(--ink)]" />{form.formState.errors[name] && <p className="mt-2 text-xs text-[var(--clay)]" role="alert">{form.formState.errors[name]?.message}</p>}</div>;
  return <form onSubmit={form.handleSubmit(submit)} className="space-y-5" noValidate>{field("name", "Name")}{field("phoneNumber", "Phone number")}<div><label htmlFor="email" className="mb-2 block text-[12px] font-medium uppercase tracking-[.12em]">Email</label><input id="email" type="email" autoComplete="email" {...form.register("email")} className="w-full border-b border-[var(--line)] bg-transparent px-0 py-3 outline-none focus:border-[var(--ink)]" />{form.formState.errors.email && <p className="mt-2 text-xs text-[var(--clay)]" role="alert">{form.formState.errors.email.message}</p>}</div><div><label htmlFor="password" className="mb-2 block text-[12px] font-medium uppercase tracking-[.12em]">Password</label><input id="password" type="password" autoComplete={register ? "new-password" : "current-password"} {...form.register("password")} className="w-full border-b border-[var(--line)] bg-transparent px-0 py-3 outline-none focus:border-[var(--ink)]" />{form.formState.errors.password && <p className="mt-2 text-xs text-[var(--clay)]" role="alert">{form.formState.errors.password.message}</p>}</div>{register && <div><label htmlFor="confirmPassword" className="mb-2 block text-[12px] font-medium uppercase tracking-[.12em]">Confirm password</label><input id="confirmPassword" type="password" autoComplete="new-password" {...form.register("confirmPassword")} className="w-full border-b border-[var(--line)] bg-transparent px-0 py-3 outline-none focus:border-[var(--ink)]" />{form.formState.errors.confirmPassword && <p className="mt-2 text-xs text-[var(--clay)]" role="alert">{form.formState.errors.confirmPassword.message}</p>}</div>}{form.formState.errors.root && <p className="text-sm text-[var(--clay)]" role="alert">{form.formState.errors.root.message}</p>}<button disabled={form.formState.isSubmitting} className="w-full bg-[var(--ink)] px-5 py-4 text-[12px] font-semibold uppercase tracking-[.14em] text-white disabled:opacity-50">{form.formState.isSubmitting ? "Please wait..." : register ? "Create account" : "Sign in"}</button><p className="text-center text-sm text-[var(--muted)]">{register ? "Already a member?" : "New here?"} <Link href={register ? "/login" : "/register"} className="text-[var(--ink)] underline">{register ? "Sign in" : "Create an account"}</Link></p></form>;
}
